import tkinter as tk
from gui import App
from dcln_gui_patch import install as install_dcln_gui
from room_gui_patch import install as install_room_gui
from char_gui_patch import install as install_char_gui
from char_skeletal_package_patch import install as install_char_skeletal_package
from uuid_gui_patch import install as install_uuid_gui
from missing_txtr_export_error_patch import install as install_missing_txtr_export_error
from skeletal_tail_patch import install as install_skeletal_tail_patch
from exact_skeletal_rig_patch import install as install_exact_skeletal_rig_patch
from mesh_partition_export_patch import install as install_mesh_partition_export_patch
from mesh_partition_outliner_cleanup_patch import install as install_mesh_partition_outliner_cleanup_patch
from blend_model_repack_patch import install as install_blend_model_repack_patch
from mesh_viewer_gui_patch import install as install_mesh_viewer_gui_patch
from ui_browser_gui_patch import install as install_ui_browser_gui_patch
from preview_orientation_patch import install as install_preview_orientation_patch
from ui_browser_library_patch import install as install_ui_browser_library_patch
from ui_browser_shape_patch import install as install_ui_browser_shape_patch
from ui_browser_scale9_blend_patch import install as install_ui_browser_scale9_blend_patch
from ui_browser_filter_patch import install as install_ui_browser_filter_patch
from ui_browser_mask_patch import install as install_ui_browser_mask_patch
from ui_browser_text_patch import install as install_ui_browser_text_patch
from ui_browser_state_inspector_patch import install as install_ui_browser_state_inspector_patch
from ui_browser_state_override_patch import install as install_ui_browser_state_override_patch
from ui_browser_state_override_gui_fix_patch import install as install_ui_browser_state_override_gui_fix_patch
from ui_browser_timeline_playback_patch import install as install_ui_browser_timeline_playback_patch
from ui_browser_performance_patch import install as install_ui_browser_performance_patch
from ui_browser_performance_followup_patch import install as install_ui_browser_performance_followup_patch
from ui_browser_game_state_patch import install as install_ui_browser_game_state_patch
from ui_browser_game_state_corpus_patch import install as install_ui_browser_game_state_corpus_patch
from ui_browser_avm2_patch import install as install_ui_browser_avm2_patch
from ui_browser_avm2_runtime_patch import install as install_ui_browser_avm2_runtime_patch
from ui_browser_avm2_runtime_corpus_patch import install as install_ui_browser_avm2_runtime_corpus_patch
from ui_browser_avm2_runtime_corpus_fix_patch import install as install_ui_browser_avm2_runtime_corpus_fix_patch
from ui_browser_avm2_runtime_compare_fix_patch import install as install_ui_browser_avm2_runtime_compare_fix_patch
from ui_browser_avm2_lifecycle_patch import install as install_ui_browser_avm2_lifecycle_patch
from ui_browser_avm2_lifecycle_inheritance_patch import install as install_ui_browser_avm2_lifecycle_inheritance_patch
from ui_browser_avm2_lifecycle_nested_event_patch import install as install_ui_browser_avm2_lifecycle_nested_event_patch
from ui_browser_avm2_dynamic_patch import install as install_ui_browser_avm2_dynamic_patch
from ui_browser_avm2_dynamic_constructor_patch import install as install_ui_browser_avm2_dynamic_constructor_patch
from ui_browser_avm2_dynamic_render_fix_patch import install as install_ui_browser_avm2_dynamic_render_fix_patch
from ui_browser_button_navigation_patch import install as install_ui_browser_button_navigation_patch
from ui_browser_button_logic_fix_patch import install as install_ui_browser_button_logic_fix_patch
from ui_browser_button_owner_fix_patch import install as install_ui_browser_button_owner_fix_patch
from ui_browser_native_callback_patch import install as install_ui_browser_native_callback_patch
from ui_browser_native_callback_priority_fix_patch import install as install_ui_browser_native_callback_priority_fix_patch
from ui_browser_async_audio_patch import install as install_ui_browser_async_audio_patch
from ui_browser_localization_patch import install as install_ui_browser_localization_patch
from ui_browser_localization_cache_patch import install as install_ui_browser_localization_cache_patch
from ui_browser_classic_button_patch import install as install_ui_browser_classic_button_patch
from ui_browser_edit_text_patch import install as install_ui_browser_edit_text_patch
from ui_browser_edit_text_fix_patch import install as install_ui_browser_edit_text_fix_patch
from ui_browser_visual_formats_patch import install as install_ui_browser_visual_formats_patch
from ui_browser_visual_formats_fix_patch import install as install_ui_browser_visual_formats_fix_patch
from mesh_viewer_uv_diagnostics_patch import install as install_mesh_viewer_uv_diagnostics_patch
from mesh_viewer_selection_patch import install as install_mesh_viewer_selection_patch
from mesh_viewer_visibility_patch import install as install_mesh_viewer_visibility_patch
import mesh_viewer
import mesh_viewer_material_shader_patch
import mesh_viewer_fur_shader_patch
import mesh_viewer_fur_renderdoc_patch
from tree_ctrl_select_patch import install as install_tree_ctrl_select_patch
from model_animation_refs_patch import install as install_model_animation_refs_patch
from char_anim_selector_patch import install as install_char_anim_selector_patch
from anim_raw_probe_patch import install as install_anim_raw_probe_patch
from anim_track_skel_map_patch import install as install_anim_track_skel_map_patch
from anim_timeline_summary_scope_patch import install as install_anim_timeline_summary_scope_patch
from blender_named_timeline_patch import install as install_blender_named_timeline_patch
from blender_preview_timeline_script_patch import install as install_blender_preview_timeline_script_patch
from blender_normal_clip_action_script_patch import install as install_blender_normal_clip_action_script_patch
from blender_embed_normal_clip_actions_patch import install as install_blender_embed_normal_clip_actions_patch
from blender_embed_character_actions_patch import install as install_blender_embed_character_actions_patch
from blender_normal_clip_fixed_basis_patch import install as install_blender_normal_clip_fixed_basis_patch
from char_required_anim_mirror_patch import install as install_char_required_anim_mirror_patch
from prefix_track_map_patch import install as install_prefix_track_map_patch
from anim_normal_clip_indices_patch import install as install_anim_normal_clip_indices_patch
from anim_normal_clip_setup_patch import install as install_anim_normal_clip_setup_patch
from anim_normal_clip_frames_patch import install as install_anim_normal_clip_frames_patch
from anim_normal_clip_values_patch import install as install_anim_normal_clip_values_patch
from anim_normal_clip_pose_patch import install as install_anim_normal_clip_pose_patch
from anim_normal_clip_bind_patch import install as install_anim_normal_clip_bind_patch
from group_accept_patch import install as install_group_accept_patch
from windows_compat import configure_root, setup_windows_process
install_skeletal_tail_patch()
install_exact_skeletal_rig_patch()
install_mesh_partition_export_patch()
install_mesh_partition_outliner_cleanup_patch()
install_blend_model_repack_patch(App)
install_dcln_gui(App)
install_room_gui(App)
install_char_gui(App)
install_char_skeletal_package(App)
install_uuid_gui(App)
install_missing_txtr_export_error(App)
install_mesh_viewer_gui_patch(App)
install_ui_browser_gui_patch(App)
install_preview_orientation_patch()
install_ui_browser_library_patch()
install_ui_browser_shape_patch()
install_ui_browser_scale9_blend_patch()
install_ui_browser_filter_patch()
install_ui_browser_mask_patch()
install_ui_browser_text_patch()
install_ui_browser_state_inspector_patch()
install_ui_browser_state_override_patch()
install_ui_browser_state_override_gui_fix_patch()
install_ui_browser_timeline_playback_patch()
install_ui_browser_performance_patch()
install_ui_browser_performance_followup_patch()
install_ui_browser_game_state_patch()
install_ui_browser_game_state_corpus_patch()
install_ui_browser_avm2_patch()
install_ui_browser_avm2_runtime_patch()
install_ui_browser_avm2_runtime_corpus_patch()
install_ui_browser_avm2_runtime_corpus_fix_patch()
install_ui_browser_avm2_runtime_compare_fix_patch()
install_ui_browser_avm2_lifecycle_patch()
install_ui_browser_avm2_lifecycle_inheritance_patch()
install_ui_browser_avm2_lifecycle_nested_event_patch()
install_ui_browser_avm2_dynamic_patch()
install_ui_browser_avm2_dynamic_constructor_patch()
install_ui_browser_avm2_dynamic_render_fix_patch()
install_ui_browser_button_navigation_patch()
install_ui_browser_button_logic_fix_patch()
install_ui_browser_button_owner_fix_patch()
install_ui_browser_native_callback_patch()
install_ui_browser_native_callback_priority_fix_patch()
install_ui_browser_async_audio_patch()
install_ui_browser_localization_patch()
install_ui_browser_localization_cache_patch()
install_ui_browser_classic_button_patch()
install_ui_browser_edit_text_patch()
install_ui_browser_edit_text_fix_patch()
install_ui_browser_visual_formats_patch()
install_ui_browser_visual_formats_fix_patch()
install_mesh_viewer_uv_diagnostics_patch()
install_mesh_viewer_selection_patch()
install_mesh_viewer_visibility_patch()
mesh_viewer_material_shader_patch._PREVIOUS_LOAD_SCENE = mesh_viewer.load_entry_scene
mesh_viewer_material_shader_patch.install()
mesh_viewer_fur_shader_patch._PREVIOUS_LOAD_SCENE = mesh_viewer.load_entry_scene
mesh_viewer_fur_shader_patch.install()
mesh_viewer_fur_renderdoc_patch.install()
install_tree_ctrl_select_patch(App)
install_model_animation_refs_patch(App)
install_char_anim_selector_patch(App)
install_anim_raw_probe_patch(App)
install_prefix_track_map_patch(App)
install_anim_normal_clip_indices_patch(App)
install_anim_normal_clip_setup_patch(App)
install_anim_normal_clip_frames_patch(App)
install_anim_normal_clip_values_patch(App)
install_anim_normal_clip_pose_patch(App)
install_anim_normal_clip_bind_patch(App)
install_anim_track_skel_map_patch(App)
install_group_accept_patch(App)
install_anim_timeline_summary_scope_patch(App)
install_blender_named_timeline_patch(App)
install_blender_preview_timeline_script_patch(App)
install_blender_normal_clip_fixed_basis_patch()
install_blender_normal_clip_action_script_patch(App)
install_char_required_anim_mirror_patch(App)
install_blender_embed_normal_clip_actions_patch()
install_blender_embed_character_actions_patch()
def main():
    setup_windows_process()
    root = tk.Tk()
    configure_root(root, min_size=(980, 700))
    App(root)
    root.mainloop()
if __name__ == '__main__':
    main()
